version: "3"
services:
    matlab:
        image: whipcarte/matlab
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/home/matlab/SSM:rw
        environment: 
        - DISPLAY=$DISPLAY
        tty: true
        stdin_open: true
        mac_address: 02:42:ac:11:00:02
    playros2:
        image: whipcarte/ssm
        volumes:
        - .:/home/ubuntu/SSM:rw
        tty: true
        stdin_open: true
        working_dir: /home/ubuntu/SSM
        # entrypoint: /home/ubuntu/SSM/ros2demo