version: "3"
services:
    matlab:
        image: whipcarte/matlab
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/home/matlab/SSM
        environment: 
        - DISPLAY=$DISPLAY
        tty: true
        stdin_open: true
        mac_address: 02:42:ac:11:00:02